Parameters:
  GitHubOAuthToken:
    Type: String
    Description: OAuth token for accessing the GitHub repository.
  GitHubOwner:
    Type: String
    Description: Owner of the GitHub repository.
  GitHubRepo:
    Type: String
    Description: Name of the GitHub repository.
    Default: test-deploy
  GitHubBranch:
    Type: String
    Default: master
    Description: Name of the GitHub branch to track.
  S3Bucket:
    Type: String
    Description: Name of S3 bucket to deploy in
  PipelineArtifactBucket:
    Type: String
    Description: Name of codepipeline bucket
    Default: codepipeline-eu-west-2-14105693034

Resources:
  Pipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactBucket
      Name: "test-frontend-deployment"
      RestartExecutionOnUpdate: true
      RoleArn: "arn:aws:iam::222370735241:role/service-role/AWSCodePipelineServiceRole-eu-west-2-test-frontend-deployment"
      Stages:
        - Name: Source
          Actions:
            - Name: SourceAction
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubOAuthToken
              OutputArtifacts:
                - Name: SourceCode
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: BuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              Configuration:
                ProjectName: "frontend-build-test"
              InputArtifacts:
                - Name: SourceCode
              OutputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
        - Name: Deploy
          Actions:
            - Name: UploadBuildArtifact
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: S3
                Version: "1"
              Configuration:
                BucketName: !Ref S3Bucket
                Extract: "true"
              InputArtifacts:
                - Name: BuildArtifact
              RunOrder: 1
