AWSTemplateFormatVersion: 2010-09-09
Description: Vue Application Deployment using S3, CloudFront and Route53

Parameters:
  DomainName:
    Type: String
    Description: The domain name to deploy the Vue application to.

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${DomainName}-vue-app"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - DomainName: !GetAtt S3Bucket.WebsiteURL
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ""
        ViewerCertificate:
          AcmCertificateArn: "arn:aws:acm:eu-west-2:222370735241:certificate/db2f70ab-d788-4987-8852-4b4d13b603c8"
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        Aliases:
          - !Ref DomainName

  Route53RecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneName: "${DomainName}."
      Comment: "DNS name for Vue application deployment"
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  VueAppURL:
    Value: !Sub "https://${DomainName}/"
