AWSTemplateFormatVersion: 2010-09-09
Description: Vue Application Deployment using S3, CloudFront and Route53

Parameters:
  DomainName:
    Type: String
    Description: The domain name to deploy the Vue application to.

Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${DomainName}-vue-app"
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html

  CloudFrontDistribution:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Enabled: true
        Origins:
          - DomainName: !Join ["", [!Ref S3Bucket, ".s3.amazonaws.com"]]
            Id: S3Origin
            S3OriginConfig:
              OriginAccessIdentity: ""
        ViewerCertificate:
          AcmCertificateArn: "arn:aws:acm:us-east-1:222370735241:certificate/20878e83-b9dc-4f86-8fa5-7345848aba43"
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2018
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
        Aliases:
          - !Sub "${DomainName}.com"

  Route53RecordSet:
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneName: !Sub "${DomainName}.com."
      Comment: "DNS name for Vue application deployment"
      Name: !Sub "${DomainName}.com."
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  VueAppURL:
    Value: !Sub "https://${DomainName}.com"
